//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamGenerator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXAMS
    {
        public EXAMS()
        {
            this.TAGS = new HashSet<TAGS>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> ExamDate { get; set; }
    
        public virtual ICollection<TAGS> TAGS { get; set; }
    }
}
