//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamGenerator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAGS
    {
        public TAGS()
        {
            this.EXAMS = new HashSet<EXAMS>();
            this.TASKS = new HashSet<TASKS>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<EXAMS> EXAMS { get; set; }
        public virtual ICollection<TASKS> TASKS { get; set; }
    }
}
